version: "3.9"

services:
  database:
    image: postgres
    container_name: database_ngnAPI
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=oficina_database
    volumes:
      - pgdata:/data/postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngnAPI
    command: npm run dev
    restart: always
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
